llm_models:

  - model_name: "openai/gpt-5.4"
    reasoning_model: true
    temperature: 1.0 # temperature seems to be ignored when reasoning_model is true
    reasoning_effort: "xhigh"
    reasoning_summary: "detailed"
    # provider_preferences: ["openai"] # does not work, don't know why

  - model_name: "z-ai/glm-5"
    reasoning_model: true
    temperature: 1.0 # temperature seems to be ignored when reasoning_model is true
    reasoning_effort: "xhigh"
    reasoning_summary: "detailed"
    provider_preferences: ["deepinfra/fp4"]

  - model_name: "google/gemini-3.1-pro-preview"
    reasoning_model: true
    temperature: 1.0 # temperature seems to be ignored when reasoning_model is true
    reasoning_effort: "xhigh"
    reasoning_summary: "detailed"
    provider_preferences: ["google-ai-studio"]

  - model_name: "anthropic/claude-sonnet-4.6"
    reasoning_model: true
    temperature: 1.0 # temperature seems to be ignored when reasoning_model is true
    reasoning_effort: "xhigh"
    reasoning_summary: "detailed"
    provider_preferences: ["anthropic"]

# Number of experimental runs to perform
runs: 1

# Type of experiment: "raw_reasoning" or "code_generation"
experiment_type: "code_generation"
