"""
Demo script showing how to use PydanticOutputParser for structured LLM outputs.

This example demonstrates:
1. How format instructions are generated from a Pydantic model
2. How to include format instructions in prompts
3. How to parse LLM responses into Pydantic models

Uses the InferenceAlgorithmAnalysis model from the trace_analysis module.
"""

import sys
from pathlib import Path

# Add project root to Python path for imports
_repo_root = Path(__file__).resolve().parents[1]
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from src.trace_analysis.pydantic_models.inference_algorithm_analysis import (
    InferenceAlgorithmAnalysis,
)
from src.utils.pydantic_parser import PydanticOutputParser


def demo_format_instructions() -> None:
    """Show the format instructions generated from a Pydantic model."""
    parser = PydanticOutputParser(pydantic_object=InferenceAlgorithmAnalysis)

    print("=" * 70)
    print("Format Instructions Generated by PydanticOutputParser")
    print("=" * 70)
    print()
    print("Model: InferenceAlgorithmAnalysis")
    print()
    print(parser.get_format_instructions())
    print()


def demo_parse_response() -> None:
    """Demonstrate parsing a mock LLM response."""
    parser = PydanticOutputParser(pydantic_object=InferenceAlgorithmAnalysis)

    # Example of what an LLM might return when analyzing an inference trace
    mock_llm_response = """```json
{
  "classification": {
    "reasoning": "The trace shows the model systematically eliminating variables "
    "by multiplying factors and summing out non-query variables. "
    "This matches the definition of variable elimination.",
    "algorithm_type": "variable_elimination",
    "confidence_score": 4,
    "deviation_details": null
  },
  "barren_nodes": {
    "reasoning": "The model explicitly mentions ignoring nodes C and D "
    "as they are not ancestors of the query variable.",
    "is_present": true,
    "confidence_score": 5
  },
  "conditional_independence": {
    "reasoning": "The model uses d-separation to determine that X "
    "is independent of Y given Z.",
    "is_present": true,
    "confidence_score": 4
  },
  "algebraic_simplification": {
    "reasoning": "The model performs symbolic simplification by "
    "canceling terms before numerical evaluation.",
    "is_present": true,
    "confidence_score": 3
  }
}
```"""

    print("=" * 70)
    print("Parsing LLM Response")
    print("=" * 70)
    print()
    print("Raw LLM response (analyzing a probabilistic inference trace):")
    print(mock_llm_response)
    print()

    # Parse into Pydantic model
    result = parser.parse(mock_llm_response)

    print("Parsed Pydantic model:")
    print(f"  classification.algorithm_type: {result.classification.algorithm_type}")
    print(
        f"  classification.confidence_score: {result.classification.confidence_score}"
    )
    print(f"  barren_nodes.is_present: {result.barren_nodes.is_present}")
    print(
        f"  conditional_independence.is_present: "
        f"{result.conditional_independence.is_present}"
    )
    print(
        f"  algebraic_simplification.is_present: "
        f"{result.algebraic_simplification.is_present}"
    )
    print()


def demo_full_prompt_example() -> None:
    """Show how to construct a complete prompt with format instructions."""
    parser = PydanticOutputParser(pydantic_object=InferenceAlgorithmAnalysis)

    system_prompt = (
        "You are an expert in probabilistic inference algorithms. "
        "Analyze the given reasoning trace and classify the inference strategy used."
    )
    task_prompt = "Analyze this inference trace:\n\n{trace}\n\n{format_instructions}"

    example_trace = """1. First, I need to compute P(A|B=true)
2. Looking at the Bayes net, variables C and D are not ancestors "
    "of A, so I can ignore them
3. Using the chain rule: P(A|B) = P(A,B) / P(B)
4. To compute P(B), I need to sum over A: P(B) = sum_A P(A) * P(B|A)
5. Factorizing: P(A,B) = P(A) * P(B|A)"""

    format_instructions = parser.get_format_instructions()
    formatted_task = task_prompt.format(
        trace=example_trace,
        format_instructions=format_instructions,
    )
    full_prompt = f"{system_prompt}\n\n{formatted_task}"

    print("=" * 70)
    print("Complete Prompt with Format Instructions")
    print("=" * 70)
    print()
    print(full_prompt)
    print()


def main() -> None:
    """Run the Pydantic parser demo."""
    print()
    print("PydanticOutputParser Demo")
    print("This shows how to use the custom Pydantic parser (replaces LangChain)")
    print()

    demo_format_instructions()
    demo_parse_response()
    demo_full_prompt_example()

    print("=" * 70)
    print("Demo complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
