"""
Utilities for executing and validating LLM-generated code.

This module provides a secure(ish) way to execute Python code generated by LLMs
for probabilistic reasoning tasks.

Security Strategy:
------------------
1. Static Analysis (AST):
   Before execution, we parse the code into an Abstract Syntax Tree (AST).
   We reject any code that attempts to import dangerous modules
   (os, sys, subprocess, shutil) or call dangerous builtins (exec, eval, open).
   This prevents the majority of
   "accidental" damage (like deleting files) or basic exploits.

2. Process Isolation (Multiprocessing):
   We execute the code in a separate `multiprocessing.Process` rather than
   using `exec()` in the main thread. This is crucial because:
   - If the generated code calls `sys.exit()`, it only kills the child process,
     not the experiment runner.
   - If the code segfaults (e.g., memory issue in pgmpy), it isolates the crash.
   - It allows us to enforce strict timeouts.

3. Timeouts:
   We enforce a strict timeout (default 10s) to prevent infinite loops from hanging
   the experiment runner.

Usage:
------
    probability = execute_and_extract_probability(llm_response, timeout=5)
"""

import ast
import logging
import multiprocessing
import re
import traceback

logger = logging.getLogger(__name__)

# Modules that are strictly forbidden for security reasons
FORBIDDEN_MODULES = {
    "os",
    "sys",
    "subprocess",
    "shutil",
    "pathlib",
    "socket",
    "requests",
    "urllib",
    "importlib",
}

# Built-in functions we generally don't want the model to use
FORBIDDEN_BUILTINS = {
    "open",
    "input",
    "eval",
    "exec",
    "__import__",
    "compile",
    "breakpoint",
}


def _is_code_safe(code_str: str) -> bool:
    """
    Statically analyze the code using AST to check for forbidden imports or calls.

    Returns True if the code appears safe enough for a research context.
    """
    try:
        tree = ast.parse(code_str)
    except SyntaxError:
        # If it's not valid Python, it can't run, so it's "safe" but will fail later.
        return True

    for node in ast.walk(tree):
        # 1. Check imports
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            names = []
            if isinstance(node, ast.Import):
                names = [n.name.split(".")[0] for n in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module:
                names = [node.module.split(".")[0]]

            for name in names:
                if name in FORBIDDEN_MODULES:
                    logger.warning(
                        f"Security Rejection: Code attempts to import "
                        f"forbidden module '{name}'"
                    )
                    return False

        # 2. Check for calls to forbidden builtins
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id in FORBIDDEN_BUILTINS
        ):
            logger.warning(
                f"Security Rejection: Code attempts to call "
                f"forbidden builtin '{node.func.id}'"
            )
            return False

    return True


def _run_in_process(code_str: str, result_queue: multiprocessing.Queue):
    """
    Function to run inside the separate process.

    Captures stdout and puts the result (or error) into the queue.
    """
    import contextlib
    import io

    # Capture stdout
    output_capture = io.StringIO()
    execution_scope = {}

    try:
        with contextlib.redirect_stdout(output_capture):
            exec(code_str, execution_scope)

        # Get output
        result_output = output_capture.getvalue()
        result_queue.put({"success": True, "output": result_output})

    except Exception as e:
        # Send error back with both exception type and message
        error_msg = traceback.format_exc()
        result_queue.put(
            {
                "success": False,
                "error": str(e),
                "error_type": type(e).__name__,
                "traceback": error_msg,
            }
        )


def execute_and_extract_probability(
    llm_response_content: str, timeout: int = 30
) -> tuple[float | None, bool, str | None, str | None]:
    """
    Extracts code from response, executes it in a secure isolated process.

    Executes code and returns the printed float probability.

    Args:
        llm_response_content: The full text response from the LLM.
        timeout: Maximum execution time in seconds.

    Returns:
        Tuple of (probability, pgmpy_library_fix_applied, exception_type,
        exception_message):
            - probability: The probability as a float if successful,
              None otherwise.
            - pgmpy_library_fix_applied: True if pgmpy API compatibility
              fix was needed.
            - exception_type: Type of exception if execution failed
              (e.g., 'ValueError'), None if successful.
            - exception_message: Exception message if execution failed
              (truncated to 1000 chars), None if successful.
    """
    # 1. Extract code blocks
    # Priority 1: <code> tags
    pattern_tags = r"<code>(.*?)</code>"
    match = re.search(pattern_tags, llm_response_content, re.DOTALL)

    if match:
        code_str = match.group(1).strip()
    else:
        # Priority 2: Markdown code blocks (```python ... ``` or just ``` ... ```)
        pattern_markdown = r"```(?:python)?\s*(.*?)```"
        match_markdown = re.search(pattern_markdown, llm_response_content, re.DOTALL)

        if match_markdown:
            code_str = match_markdown.group(1).strip()
        else:
            logger.warning(
                "No <code> block or markdown code block found in LLM response."
            )
            return (
                None,
                False,
                "NoCodeBlockError",
                "No <code> block or markdown code block found in LLM response.",
            )

    # 1.5. Fix pgmpy API compatibility issues (old API -> new API)
    # Models used older versions of pgmpy where BayesianModel/BayesianNetwork existed.
    # In current pgmpy, these are deprecated/removed in favor of DiscreteBayesianNetwork
    original_code = code_str
    code_str = code_str.replace(
        "from pgmpy.models import BayesianModel",
        "from pgmpy.models import DiscreteBayesianNetwork as BayesianModel",
    )
    code_str = code_str.replace(
        "from pgmpy.models import BayesianNetwork",
        "from pgmpy.models import DiscreteBayesianNetwork as BayesianNetwork",
    )

    # Track if fix was applied
    pgmpy_library_fix_applied = code_str != original_code

    # 2. Static Safety Check (AST)
    if not _is_code_safe(code_str):
        return (
            None,
            pgmpy_library_fix_applied,
            "SecurityError",
            "Code failed security check (forbidden imports or builtins)",
        )

    # 3. Execute in isolated process
    result_queue = multiprocessing.Queue()
    process = multiprocessing.Process(
        target=_run_in_process, args=(code_str, result_queue)
    )

    try:
        process.start()
        process.join(timeout=timeout)

        if process.is_alive():
            logger.warning(f"Execution timed out after {timeout} seconds. Terminating.")
            process.terminate()
            process.join()
            return (
                None,
                pgmpy_library_fix_applied,
                "TimeoutError",
                f"Execution timed out after {timeout} seconds",
            )

        if result_queue.empty():
            logger.warning("Process finished but returned no result (crashed?).")
            return (
                None,
                pgmpy_library_fix_applied,
                "ProcessError",
                "Process crashed or terminated without returning result",
            )

        result = result_queue.get()

        if not result["success"]:
            error_str = str(result.get("error", "Unknown error"))
            # Truncate error message to 1000 characters
            error_message = error_str[:1000] if len(error_str) > 1000 else error_str

            # Get exception type from the subprocess result
            exception_type = result.get("error_type", "UnknownError")

            logger.warning(f"Runtime error executing code: {error_message}")
            return None, pgmpy_library_fix_applied, exception_type, error_message

        raw_output = result["output"].strip()

    except Exception as e:
        exception_type = type(e).__name__
        error_message = str(e)[:1000]  # Truncate to 1000 chars
        logger.error(f"System error managing process execution: {e}")
        return None, pgmpy_library_fix_applied, exception_type, error_message

    # 4. Parse output (expecting a single float on stdout)
    try:
        return float(raw_output), pgmpy_library_fix_applied, None, None
    except ValueError:
        error_message = f"Could not parse float from code output: '{raw_output[:200]}'"
        logger.warning(error_message)
        return None, pgmpy_library_fix_applied, "ValueError", error_message[:1000]
